# fly.toml app configuration file generated for streamlit-2-hrnq on 2026-03-09T13:35:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'streamlit-2-hrnq'
primary_region = 'ams'

[build]

[env]
  PORT = "8501"

[http_service]
  internal_port        = 8501
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ['app']

  [[http_service.checks]]
    grace_period = "30s"
    interval     = "15s"
    method       = "GET"
    path         = "/_stcore/health"
    timeout      = "10s"

[[vm]]
  memory   = "512mb"
  cpu_kind = "shared"
  cpus     = 1
